Story/vspc 116
diging/virtual-spaces-2.0 pull request #153
Opened 2020-08-14 17:56 UTC by prjadhav14

This development is to add text blocks on space images at the location where user clicks on the image and showing the saved text block on public site.

2020-08-14 19:59 UTC, jdamerow commented
I'm gonna let @coder-aakash994 and @Sagar-k93 review this one first :)

2020-08-26 20:23 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.jsp
> +        console.log(textB.value);
remove console logs

2020-08-26 20:23 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.jsp
> +  }
indentations are off

2020-08-26 20:24 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.jsp
> +		block = $('<span data-link-id="${block.id}" class="spaceLink-${block.id} textDiv"><textarea class="textBlock" style="height:${block.heigth}px; width:${block.width}px;" readonly>${block.spaceTextBlo
merge with line 256

2020-08-26 20:25 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.jsp
> +	        	console.log(blockData);
remove

2020-08-26 20:28 UTC, jdamerow commented
Make it so, Jenkins.

2020-08-26 20:36 UTC, jdamerow commented
And a couple of things:
staff side:
- the width should be a percentile of the image width (same with height), otherwise it'll get difficult when resizing
- the box size should be adjustable in both directions width and height (right now it's only height)
- there should be a button to add a new test box, same as with the other elements.
- the text box in the modal, should be bigger
- the text box on the staff side should show the text
- text boxes need to be editable and deletable

public side
- the text box on the public side should not be adjustable, only collapsable

2020-10-14 19:41 UTC, prjadhav14 commented
Mistakenly added VSPC-120 id on last commit instead of VSPC-116.

2020-10-16 18:32 UTC, jdamerow requested changes

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/model/impl/SpaceTextBlock.java
> +    private String text;
you probably want this to be a `@Lob`

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/SpaceTextBlockManager.java
> +    public ISpaceTextBlockDisplay updateTextBlock(String id, Float positionX, Float positionY, String textBlockIdValueEdit,
what does that mean: `textBlockIdValueEdit`? Is that the text block id? if so, that should be the name.

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/SpaceTextBlockManager.java
> +            if(spaceTextBlockDisplay.isPresent()) {
It would be a lot either to understand if you first get the block and the display, return if one of them doesn't exist; if both exist, do the update.

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/SpaceTextBlockManager.java
> +}
class needs test cases

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddSpaceTextBlockController.java
> +                    throws NumberFormatException, SpaceDoesNotExistException, IOException, ImageCouldNotBeStoredException {
where is `NumberFormatException` thrown and why? you should probably not throw that but handle it if it's actually thrown.

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddSpaceTextBlockController.java
> +                    throws NumberFormatException, SpaceDoesNotExistException, IOException, ImageCouldNotBeStoredException {
pretty much the same with all the exceptions

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/EditSpaceTextBlockController.java
> +//        }
remove if not needed

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/EditSpaceTextBlockController.java
> +        //return success(display.getLink().getId(), display.getId(), display.getPositionX(), display.getPositionY(), display.getRotation(),null,title,displayType,linkedModuleId,null);
same

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/exhibition/space.jsp
>  }
needs to be merged with thymeleaf templates

2020-10-16 18:32 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.jsp
>  <p></p>
thymeleaf

2020-10-28 13:28 UTC, jdamerow commented
Please reopen when VSPC-120 is merged, otherwise it's difficult to see what has been changed in this branch.

2020-10-28 13:28 UTC, closed without merging