Story/vspc 86
diging/virtual-spaces-2.0 pull request #155
Opened 2020-08-14 23:01 UTC by prjadhav14

This development involves adding indicators for space links in staff screens and in the linked space dropdown when user creates a new link or edits existing link.

2020-08-26 17:46 UTC, coder-aakash994 commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.jsp
> +		//$(".spaceLink-${link.link.id}").append(unpublishedSpaceElement);
remove comment lines

2020-08-26 20:12 UTC, jdamerow commented
Make it so, Jenkins.

2020-08-26 20:16 UTC, jdamerow commented
what aakash said. afterwards should be good.

2020-08-28 13:00 UTC, jdamerow commented
Make it so, Jenkins.

2020-08-28 13:07 UTC, jdamerow commented
there is actually an issue I missed before. For adding a new space link, the drop down is wider than the modal:
![image](https://user-images.githubusercontent.com/8881141/91563991-df64e700-e90d-11ea-9835-b1f6be543f98.png)

2020-08-28 18:33 UTC, jdamerow commented
If I create a new space link and choose an unpublished space, I have to reload the page to get the alert icon.

2020-09-01 16:30 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddSpaceLinkController.java
> +        linkNode.put("likedSpaceStatus", spaceManager.getSpace(linkedSpaceId).getSpaceStatus().toString());
do you mean "linkedSpaceStatus"?

2020-09-01 16:32 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.jsp
> +		$("#space").append(unpublishedSpaceElement);
if `show` is false, then `unpublishedSpaceElement` is undefined here, isn't it?

2020-09-01 16:33 UTC, jdamerow commented
Make it so, Jenkins.

2020-09-01 16:39 UTC, jdamerow commented
- When I delete a link to an unpublished space, the warning triangle stays.
- when I edit a space link from an unpublished to a published space, the warning triangle stays.

2020-09-01 16:44 UTC, jdamerow commented
Also, it seems like when I have a link to an unpublished space, I can't delete any other link anymore. And there are other oddities but not sure if that's related to the changes in this ticket or generally a problem (https://diging.atlassian.net/browse/VSPC-119).

2020-09-01 19:54 UTC, jdamerow commented
there are still issues.
- I create a link to an unpublished space
- I click the link to edit it
- i select a published space
- i click save, nothing happens
- when I reload the page, the changes have been persisted (the link links to a published space), but something seems to go wrong after the save has been executed (before the modal closes)

It works the other way though, I can choose an unpublished space and that works fine.

2020-09-04 18:34 UTC, prjadhav14 commented
> there are still issues.
> 
>     * I create a link to an unpublished space
> 
>     * I click the link to edit it
> 
>     * i select a published space
> 
>     * i click save, nothing happens
> 
>     * when I reload the page, the changes have been persisted (the link links to a published space), but something seems to go wrong after the save has been executed (before the modal closes)
> 
> 
> It works the other way though, I can choose an unpublished space and that works fine.

is working fine in local.

2020-09-04 19:31 UTC, jdamerow commented
This seems to be the problem:
```
</pre><p><b>Root Cause</b></p><pre>java.lang.NullPointerException
	edu.asu.diging.vspace.web.staff.EditSpaceLinkController.editSpaceLink(EditSpaceLinkController.java:53)
```

2020-09-08 20:22 UTC, jdamerow commented
still throwing a nullpointer:
```
</pre><p><b>Root Cause</b></p><pre>java.lang.NullPointerException
	edu.asu.diging.vspace.web.staff.EditSpaceLinkController.editSpaceLink(EditSpaceLinkController.java:57)
```

2020-09-09 17:00 UTC, jdamerow requested changes
just those few indentation issues and then it should be good to go

2020-09-09 17:00 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.jsp
> +			}
indentation

2020-09-10 13:34 UTC, merged