Story/vspc 55
diging/virtual-spaces-2.0 pull request #167
Opened 2020-12-02 20:55 UTC by prjadhav14

This ticket is about filtering the image list using the selected image category. This is achieved using jQuery and a hidden column in the table containing image category values.

2020-12-03 17:40 UTC, jdamerow commented
This only filters the currently visible data in the table, doesn't it? Not all data? So if I have 5 pages it will only show me the results for a specific category that are on that one page, not all? It should filter all data (make a call to the server).

2020-12-03 17:43 UTC, prjadhav14 commented
> This only filters the currently visible data in the table, doesn't it? Not all data? So if I have 5 pages it will only show me the results for a specific category that are on that one page, not all? It should filter all data (make a call to the server).

Okay, is pagination expected if we give a server call and get more than 10 items on the list?

2020-12-03 17:45 UTC, jdamerow commented
yes, you shouldn't have to change much, except the method that is called to retrieve the data (but with the same page, etc.)

2020-12-14 15:57 UTC, jdamerow requested changes

2020-12-14 15:57 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +        page = StringUtils.isEmpty(page) ? "1" : page;
switch with line 82 (declare variables as close to where they are needed as possible)

2020-12-14 15:57 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +            pageNo = 1;
log a warning here

2020-12-14 15:57 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +        List<IVSImage> imagesList = imageService.getImages(pageNo, sortedBy, order);
you should only get the images from the db that have a certain category (your total image count is wrong here too, isn't it?). Also, this should probably happen in the `listSpaces` method and pass the filter as query parameters. A lot of duplicate code here.

2020-12-16 21:39 UTC, jdamerow requested changes

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ImageService.java
> +        Page<IVSImage> images = imageRepo.findByCategoriesLike(sortByRequestedField, category);
Is there a reason that you do a like query instead of the regular query?

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ImageService.java
> +        return imageRepo.findByCategoriesLike(category).size();
you can do a `countBy` query and let the db do the counting

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ImageService.java
> +        int count = imageRepo.findByCategoriesLike(category).size();
same as above

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ImageService.java
> +        return (count % pageSize==0) ? count / pageSize:(count / pageSize) + 1;
let's change the spacing so it's clear what belongs together
`coutn/pageSize : (count/pageSize)+1;`

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +        return String.format("redirect:/staff/images/list/1?imageCat=%s",(imageCategory != null ? imageCategory : "Show All"));
let's use `all` instead of `Show all` since it's a parameter

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +        if(imageCategory.equals("Show All")) {
should not be hard-coded; especially since it's used before put in enum or constant in an interface

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +        else {
code style

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +            model.addAttribute("totalPages", imageService.getTotalPagesForSelectedFilter(ImageCategory.valueOf(imageCategory)));
since you're passing the category here into the method `getTotalPages` is descriptive enough as a method name

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +            model.addAttribute("totalPages", imageService.getTotalPagesForSelectedFilter(ImageCategory.valueOf(imageCategory)));
javadoc should do the rest of the explaining

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +            model.addAttribute("totalImageCount", imageService.getTotalImageCountForSelectedFilter(ImageCategory.valueOf(imageCategory)));
same as above

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> +            images = imageService.getImagesByCategory(pageNo, ImageCategory.valueOf(imageCategory), sortedBy, order);
same as above

2020-12-16 21:39 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/images/imagelist.html
> +                                    + catTag)}]]</option>
let's format that better
```
<option ...>
   [[...]]
</option>
```

2021-01-07 21:26 UTC, jdamerow requested changes

2021-01-07 21:26 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ImageService.java
> +    public List<IVSImage> getImages(int pageNo, ImageCategory category, String sortedBy, String order) {
is this method any different from the above `getImages`? it's only the find line, isn't it? Should be one method.

2021-01-07 21:26 UTC, closed without merging