VSPC 139
diging/virtual-spaces-2.0 pull request #170
Opened 2020-12-14 07:03 UTC by prjadhav14

Creating a new pull request to compare branch with VSPC 120

2020-12-14 15:36 UTC, jdamerow requested changes

2020-12-14 15:36 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddExternalLinkController.java
> +        Float y_val = (displayAttributes.getHeight() * new Float(y))/spaceManager.getSpace(id).getImage().getHeight();
Please follow our code style (variable naming) and remove duplicate code (this seems to be the same as for the other two link types in the other controllers)

2020-12-14 15:36 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +        link.css('top', linkPosY + posY);
indentation and remove logs

2020-12-14 15:36 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +			});
since we're using jquery, let's use that consistently (the whole block mixes  jquery and javascript.

2020-12-14 15:36 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +			[/]
same as above. and please remove all console logs.

2020-12-14 15:36 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +
indentations

2020-12-14 15:36 UTC, jdamerow commented
Make it so, Jenkins.

2020-12-14 15:49 UTC, jdamerow commented
not sure what's happening, but the pop up doesn't seem to have changed (right side is still pretty spacious, big font etc) and the image is still the same size. Now, however, the links are not positioned correctly.
![image](https://user-images.githubusercontent.com/8881141/102102623-07fbe880-3dfa-11eb-8566-32d12d433d40.png)

2020-12-16 08:46 UTC, prjadhav14 commented
Reopening to test functionalities

2020-12-16 08:46 UTC, prjadhav14 commented
Reopening to test link positions fix on the modal view

2020-12-16 08:53 UTC, prjadhav14 commented
Reopening to test link positions fix on the modal view

2020-12-16 09:21 UTC, prjadhav14 commented
Reopening to test link positions fix on the modal view

2021-01-13 21:49 UTC, prjadhav14 commented
Reopening to test.

2021-01-15 16:06 UTC, prjadhav14 commented
Reopening to debug

2021-01-15 16:52 UTC, jdamerow commented
Make it so, Jenkins.

2021-01-15 17:27 UTC, closed without merging