changed CSS properties to place bootstrap menus wrt to screens
diging/virtual-spaces-2.0 pull request #180
Opened 2021-01-20 22:24 UTC by ashmichheda

2021-01-21 14:17 UTC, jdamerow requested changes

2021-01-21 14:17 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/exhibition/space.html
> +} */
remove comments if not needed

2021-01-21 14:17 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/exhibition/space.html
> +			else if (window.matchMedia(maxWidth).matches){
indentation

2021-01-21 14:17 UTC, jdamerow commented
Make it so, Jenkins.

2021-01-21 14:30 UTC, jdamerow commented
It's actually almost less usable now. The links are partially not displayed on my phone. The menu should open above the image like the bootstrap menus do, big enough to select them with a finger.
![image](https://user-images.githubusercontent.com/8881141/105364479-332ce100-5bcb-11eb-9937-bf60ca0aa2b1.png)

2021-01-21 14:30 UTC, closed without merging

2021-01-26 21:05 UTC, ashmichheda commented
I went through an example of bootstrap menu. By default, the menu appears extended when the screen is maximized and they collapse when the screen is minimized.
But in our application, the menu is already collapsed when maximized and when the screen is minimized we still want the menu to be collapsed. 
Only on small screens, it should show above the image. I am not sure.

I am going through the below example.

[Boostrap NavBar](https://getbootstrap.com/docs/3.4/examples/navbar/)

Is this the right one to refer as an example?

2021-01-27 17:14 UTC, ashmichheda commented
Should the menu be along with the sign out and dashboard icons for small screens?