Story/vspc 93
diging/virtual-spaces-2.0 pull request #189
Opened 2021-02-08 23:15 UTC by ashmichheda

2021-02-09 15:17 UTC, jdamerow commented
please reread the PR guidelines.

2021-02-09 20:19 UTC, jdamerow requested changes
Have you looked at the PR after you've opened it? according to this, you've changed a lot of these files completely, which I don't believe you did?

2021-02-09 20:19 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/data/ModuleRepository.java
> +}
what has changed in this file?

2021-02-09 20:19 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/layouts/navbar.html
> +	</body>
what has actually been changed in this file?

2021-02-09 20:19 UTC, closed without merging

2021-02-09 20:36 UTC, ashmichheda commented
When I merged code from Develop to my branch. I saw that these files were updated. So I have just changed the UNIX file encoding to all these files.

2021-02-09 20:37 UTC, ashmichheda commented
Am I supposed to do anything else as well?

2021-02-10 14:57 UTC, jdamerow commented
DashboardController does not seem to have unix file endings. Any file that shows up as changed although you didn't change it, make sure the change is necessary, and make a comment why it has been changed.