Story/vspc 95
diging/virtual-spaces-2.0 pull request #190
Opened 2021-02-15 19:24 UTC by Sagar-k93

Changes to make the public slides page. The contents of the slide are scroll-able but the slide control buttons are to be static.

2021-02-15 19:27 UTC, Sagar-k93 commented on vspace/src/main/java/edu/asu/diging/vspace/core/model/ISpaceLink.java
>  public interface ISpaceLink extends ILink<ISpace> {
Indentation and line ending changes.

2021-02-15 19:48 UTC, Sagar-k93 commented on vspace/src/main/java/edu/asu/diging/vspace/core/model/IPrefix.java
> +package edu.asu.diging.vspace.core.model;
Line ending changes.

2021-02-15 19:50 UTC, Sagar-k93 commented on vspace/src/main/java/edu/asu/diging/vspace/core/model/IdPrefix.java
> -public enum IdPrefix {
Line ending changes.

2021-02-15 22:14 UTC, Sagar-k93 commented on vspace/src/main/webapp/WEB-INF/views/login.html
> -<html layout:decorate="~{layouts/main}">
Line ending changes.

2021-02-15 22:20 UTC, Sagar-k93 commented on vspace/src/main/java/edu/asu/diging/vspace/core/model/impl/Space.java
>      @Id
Spacing changes in this file.

2021-02-15 22:24 UTC, Sagar-k93 commented on vspace/src/main/java/edu/asu/diging/vspace/web/HomeController.java
> -package edu.asu.diging.vspace.web;
Spaces and line ending changes.

2021-02-15 22:24 UTC, Sagar-k93 commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddSpaceController.java
> -package edu.asu.diging.vspace.web.staff;
Line ending changes.

2021-02-15 22:25 UTC, Sagar-k93 commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/ListImagesController.java
> -package edu.asu.diging.vspace.web.staff;
Line ending changes.

2021-02-15 22:25 UTC, Sagar-k93 commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/SequenceController.java
> -package edu.asu.diging.vspace.web.staff;
Line ending changes.

2021-02-17 19:51 UTC, jdamerow requested changes
Please reread pull request guidelines before I look at this again.

2021-02-17 19:51 UTC, jdamerow commented on Docker/.gitignore
> -/.DS_Store
should not be deleted

2021-02-17 19:51 UTC, jdamerow commented on .project
> +</projectDescription>
let's not commit this file

2021-02-17 19:51 UTC, jdamerow commented on vspace/.classpath
> -<?xml version="1.0" encoding="UTF-8"?>
this file seems to have the wrong line endings

2021-02-17 19:51 UTC, closed without merging