Story/vspc 115
diging/virtual-spaces-2.0 pull request #193
Opened 2021-02-25 22:58 UTC by Sagar-k93

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

we need another content block but for videos. For now, let's have the video stored somewhere else (e.g. Youtube or another hosting service) and include them via URL. 
  
## Anything else the reviewer needs to know?

2021-02-26 14:23 UTC, jdamerow requested changes

2021-02-26 14:23 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/model/IVSMedia.java
> +// IVSVideo and IVSImage classes.
this is not proper javadoc

2021-02-26 14:23 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/model/impl/VideoBlock.java
> +    private IVSVideo video;
order is wrong; first class variables then constructor.

2021-02-26 14:23 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ContentBlockManager.java
> +     *           functions returns nothing.
this is a method (not a function) and it never returns anything (its return type is `void`)

2021-02-26 14:23 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddVideoBlockController.java
> +        return new ResponseEntity<>(videoId, HttpStatus.OK);
what happens if videoFile is null and url is null (or empty)?

2021-02-26 14:23 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/EditVideoBlockController.java
> +        return new ResponseEntity<String>(HttpStatus.OK);
same as before, what if neither video nor url is send? Also, this seems like it's almost exactly the same code as for adding videos: DRY.

2021-02-26 14:23 UTC, jdamerow commented
there is a codefactor warning.

2021-02-26 14:24 UTC, jdamerow commented
Make it so, Jenkins.

2021-02-26 14:39 UTC, jdamerow commented
For the UI:
- when I add a youtube link, the video says "youtube refused to connect". If I can't just take the url, there need to be instructions.
- the button is too close to the bottom:
![image](https://user-images.githubusercontent.com/8881141/109313045-c2a26100-7815-11eb-92a8-a5b177589b26.png)
- how do I edit a video? double-clicking on it doesn't do anything.
-  clicking "Embed video" if no url and no file is provided, shouldn't be possible or should show an error message.
- video blocks need to show up on the public site
- there should be a title for videos that is shown like a figure heading

2021-03-22 17:29 UTC, jdamerow requested changes

2021-03-22 17:29 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ContentBlockManager.java
> +        {
code style

2021-03-22 17:29 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ContentBlockManager.java
> +            if (url == null || url.equals("")) {
that's an odd if condition, why not `if video != null`? More straight forward and easier to understand.

2021-03-22 17:29 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddVideoBlockController.java
> +                throw new VideoCouldNotBeStoredException();
in this case it should show an appropriate error message. Could not be stored is incorrect since there was nothing to store.

2021-03-22 17:29 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddVideoBlockController.java
> +            return new ResponseEntity<>(mapper.writeValueAsString(node), HttpStatus.BAD_REQUEST);
bad request means, the request was malformed, but this could happen if there is an errr server side, isn't there?

2021-03-22 17:31 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/VideoFactoryTest.java
> +}
test cases for content block manager methods are missing.

2021-03-22 17:31 UTC, jdamerow commented
Make it so, Jenkins.

2021-03-22 17:54 UTC, jdamerow commented
- let's add an edit icon for editing videos. You have to know that you can't double click on the video but on the white space around it to edit it. It would be a lot more straight forward to just have an edit icon.
- there is something off with the modal (you're not resetting the form correctly or something):
   - when double click the video to edit and then just cancel the modal
   - then click on adding a new video
   - cancel and then edit the exiting video again
   - -> it shows me all three fields: title, select video, and url
- similarly if I first open the edit modal (for an embedded url), cancel, and then add a new video, the fields for uploading a video are disabled.
- uploaded videos don't work on the public site

2021-11-05 16:14 UTC, jdamerow requested changes
there are code factor warnings

2022-01-03 20:16 UTC, jdamerow requested changes

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				}
there seems to be a lot of duplicate code in the above if/else statement. That should be more DRY.

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				}
also, indentation needs fixing

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				});
indentation

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				});
indentation

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				});
indentation

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				});
indentation

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +					//$("#uploadLink").tab('show');
remove if not needed

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +			   console.log(title);
remove

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +			});
indentation needs some fixing in the above blocks

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/main/webapp/resources/extra/Module_1_slideshow_1.css
> +    }
file has wrong line endings

2022-01-03 20:16 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/VideoFactoryTest.java
> +}
?

2022-03-04 15:00 UTC, jdamerow requested changes
there are a bunch of unaddressed comments

2022-03-04 15:00 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				});
?

2022-03-04 15:00 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +			});
?

2022-03-14 14:22 UTC, jdamerow requested changes

2022-03-14 14:22 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ContentBlockManager.java
> +        IVideoBlock vidBlock = null;
merge with line 240

2022-03-14 14:22 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				});
too much indentation; makes it much harder to read.

2022-03-14 14:22 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				});
see above

2022-03-14 14:22 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +			});
?

2022-03-14 14:22 UTC, jdamerow commented
Make it so, Jenkins.

2022-03-14 14:53 UTC, jdamerow commented
Please go carefully through all comments and fix the indentation. They don't have to be perfect in HTML pages but they should be 10 spaces off to the rest. It's really easy to see if you look at the files tab.

Also, when I upload a .mov file, it doesn't show. It shows the progress bar but not the picture. Unless we can fix it so it plays .mov files, there should at least be a sentence about what videos can be uploaded in the UI.

2022-03-21 13:52 UTC, jdamerow requested changes

2022-03-21 13:52 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +				}
?

2022-03-21 13:52 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> + 				});
indentation

2022-03-21 13:52 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +			</div>
indentation

2022-03-24 15:59 UTC, jdamerow commented
Make it so, Jenkins.

2022-03-24 16:46 UTC, jdamerow commented
Make it so, Jenkins.

2022-03-24 18:43 UTC, jdamerow commented
A video I took with my phone isn't showing (it's a .mov file). If there is something special that needs to be done then instructions for that should be added to the UI.

2022-03-28 19:54 UTC, jdamerow commented
Make it so, Jenkins.

2022-03-28 20:01 UTC, jdamerow commented
It seems I cannot just edit the title of an uploaded video. When I click the edit button and enter a title, then click upload video, nothing seems to happen but when I go to the public site, the video is gone. It needs to be possible to edit just the title or exchange the video. 
Also, now, the slide page is not loading: https://diging-dev.asu.edu/vspace-dev/staff/module/MOD1/slide/SLI000000003

2022-04-06 15:20 UTC, jdamerow requested changes

2022-04-06 15:20 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ContentBlockManager.java
> +    public void updateVideoTitle(IVideoBlock videoBlock,  String title){
just make this a save method and pass in the changed block object with the changed title.

2022-04-07 18:29 UTC, jdamerow commented
There are some issues here:
`GET https://diging-dev.asu.edu/vspace-dev/staff/module/MOD1/slide/SLI000000003 net::ERR_INCOMPLETE_CHUNKED_ENCODING 200`

also:
- when I add a second video right after the first one, the title field still has the previous value in it

2022-04-07 18:34 UTC, jdamerow commented
- and let's call the button "Update Video" when updating
- and I deleted the video I added second, then tried to delete the video I added first. I got an error message that there was an error, then the alert vanished (it was way too far right btw to be able to read it) and the delete button vanished with it.
![image](https://user-images.githubusercontent.com/8881141/162272988-b86529f7-b821-457b-b9a5-cab9da42244f.png)

you can also reproduce it by just adding two videos and then trying to delete one (without page relload in between)

2022-04-11 16:28 UTC, jdamerow commented
This one is still not working: https://diging-dev.asu.edu/vspace-dev/staff/module/MOD1/slide/SLI000000003
The deletion bug is still happenings. Maybe it's the order of type of video blocks: first a youtube one, then an uploaded one.

2022-04-14 17:16 UTC, jdamerow commented
Make it so, Jenkins.

2022-05-05 16:45 UTC, jdamerow requested changes

2022-05-05 16:45 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/EditVideoBlockController.java
> +}
file has wrong line endings

2022-05-05 16:45 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/VideoBlockFactoryTest.java
> +package edu.asu.diging.vspace.core.services.impl;
wrong package

2022-05-05 16:45 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/VideoFactoryTest.java
> +package edu.asu.diging.vspace.core.services.impl;
wrong package

2022-05-05 16:45 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/ContentBlockManagerTest.java
> +    public void test_createVideoBlock_withURLsuccess()
what about other scenarios with an uploaded videos, or when this method fails? Needs more test cases.

2022-11-17 19:51 UTC, tusanand commented
Addressed all review comments

2022-11-17 22:03 UTC, jdamerow requested changes

2022-11-18 18:25 UTC, tusanand commented
Changed line endings along with other review comments

2023-02-14 20:46 UTC, jdamerow commented
Make it so, Jenkins.

2023-02-14 21:07 UTC, merged