Story/vspc 116 2
diging/virtual-spaces-2.0 pull request #199
Opened 2021-04-05 17:54 UTC by prjadhav14

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
Adding provisions for staff user to add text blocks on space images and making those visible on staff site

...Put description here...
  
## Anything else the reviewer needs to know?

... describe here ...

2021-04-07 20:06 UTC, jdamerow requested changes

2021-04-07 20:06 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/SpaceTextBlockManager.java
> +        textBlock=spaceTextBlockRepo.save((SpaceTextBlock) textBlock);
`textBlock` isn't needed afterwards, is it? so no need to assign it here.

2021-04-07 20:06 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/DeleteLinkController.java
> +    @RequestMapping(value = "/staff/space/{id}/textBlock/{blockId}", method = RequestMethod.DELETE)
deleting a text block shouldn't be in the DeleteLinkController

2021-04-07 20:06 UTC, jdamerow commented
Make it so, Jenkins.

2021-04-07 20:10 UTC, jdamerow commented
clickin on the save button doesn't do anything.

2021-04-07 20:11 UTC, jdamerow commented
```
om.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column &#39;text&#39; at row 1
	com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
```

2021-04-07 22:38 UTC, prjadhav14 commented
> ```
> om.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column &#39;text&#39; at row 1
> 	com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
> 	com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
> ```

To resolve this we would need to run the below SQL scripts since String text is updated to @Lob which may not be taking effect since the table is already created in the environment.

drop table SpaceTextBlockDisplay;
drop table SpaceTextBlock;
commit;

2021-04-13 20:33 UTC, jdamerow commented
Make it so, Jenkins.

2021-04-13 20:42 UTC, jdamerow commented
- How can a text block be edited? (ah, that only seems to work after reloading the page)
- right now I can type into a text block after it has been created but that doesn't seem to do anything (it's not saved)
- on the staff side, the text block should show the actual text.
- the input field for the text needs to be bigger since it might hold quite a bit of text
- how can I delete a text block (same as above, only shows up after reloading the page, but the delete button only empties the form but doesn't seem to delete the text block)
- I can click on the image and the text block moves after I added it (but that doesn't change the actual text block)
- the text block should have a black or white lightly transparent background or something (talk to Adhvik how to make that nice looking)

2021-04-26 14:28 UTC, jdamerow requested changes

2021-04-26 14:28 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddSpaceTextBlockController.java
> +    @RequestMapping(value = "/staff/space/{id}/textBlock", method = RequestMethod.POST)
let's lowercase `textblock`

2021-04-26 14:28 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/DeleteSpaceTextBlockController.java
> +    @RequestMapping(value = "/staff/space/{id}/textBlock/{blockId}", method = RequestMethod.DELETE)
same as above

2021-04-26 14:28 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/EditSpaceTextBlockController.java
> +    @RequestMapping(value = "/staff/space/link/textBlock/{id}", method = RequestMethod.POST)
same as above

2021-04-26 14:28 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/exhibition/space.html
> +    			$("#space").append(block);
indentations

2021-04-26 14:28 UTC, jdamerow commented
Make it so, Jenkins.

2021-04-26 14:36 UTC, jdamerow commented
- textbox can't be changed after creation when using the corner (not the input fields)
- when using the input fields, there is something off. When I change the width and then the hieght, the width gets reset or something (and the other way around)
- I can change the size of the textbox by dragging the corner but that actually changes the textbox. I shouldn't be able to change the textbox if it doesn't actually change the size (hope that makes sense).

2021-05-03 18:50 UTC, jdamerow commented
Resolve conflicts please

2021-05-03 20:24 UTC, jdamerow commented
Make it so, Jenkins.

2021-05-03 20:33 UTC, jdamerow commented
- the "edit text block" should be "Save" and the buttons need to have a little bit of padding at the bottom:
![image](https://user-images.githubusercontent.com/8881141/116929916-12920f80-ac2d-11eb-8348-ba0c0c7b27fc.png)
- the sizing is different on staff and public page:
staff:
![image](https://user-images.githubusercontent.com/8881141/116929974-250c4900-ac2d-11eb-9e5c-df243cd65409.png)
public:
![image](https://user-images.githubusercontent.com/8881141/116929989-2b022a00-ac2d-11eb-9bf3-1a6b58d11ab2.png)
- resizing the public page window does this:
![image](https://user-images.githubusercontent.com/8881141/116930028-36555580-ac2d-11eb-9727-011a738b4f51.png)

2021-05-12 15:01 UTC, jdamerow commented
Make it so, Jenkins.

2021-05-12 15:21 UTC, jdamerow commented
staff side:
- when editing a text block: I click on the text block, it opens the edit modal. when I click somewhere else to move the text block, it duplicates it.
- when creating a text block, the spinning icon is not shown. It just takes a long time for the modal to close, which is confusing since the user doesn't know if it didn't work or if it is just slow.
- on the main image (not the modal), the right bottom corner shouldn't let the user change the size of the box since that doesn't actually change the size of the box.

2022-04-18 15:00 UTC, jdamerow requested changes
CodeFactor also found an issue.

2022-04-18 15:00 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/SpaceTextBlockManagerTest.java
> +
test cases for not succeeding are missing (e.g. if text block to be deleted doesn't exist).

2022-05-18 16:21 UTC, jdamerow requested changes

2022-05-18 16:22 UTC, jdamerow commented
Make it so, Jenkins.

2022-08-30 18:31 UTC, jdamerow requested changes
there are unaddressed comments

2022-08-30 18:31 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +    var textB = document.getElementById('textB'),
?

2022-08-30 18:31 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +    var width = parseInt($("#bgImage").css("width"));
?

2022-09-06 15:41 UTC, jdamerow requested changes

2022-09-06 15:41 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/SpaceTextBlockManagerTest.java
> +    public void test_updateTextBlock_textblockIdempty_failed(){
fix camel case

2022-09-06 15:41 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/SpaceTextBlockManagerTest.java
> +    public void test_updateTextBlock_textblocDisplayIdempty_failed(){
fix camel case and spelling  mistake

2022-09-06 15:41 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/SpaceTextBlockManagerTest.java
> +    }
this method never calls `managerToTest`, does it?

2022-09-06 15:41 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/SpaceTextBlockManagerTest.java
> +        Mockito.verify(spaceTextBlockDisplayRepo, Mockito.never()).save(spaceTextBlockDisplay);
same here, never calls `managerToTest`

2022-09-06 15:41 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +            tWidth = textModalBlock.clientWidth;
indent

2022-09-06 15:41 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +	$(".deletedSpaceClass").remove();
indent

2022-09-06 15:41 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +	modalBgImageWidth = parseInt($("#bgImage").css("width"));
indent

2022-09-06 15:41 UTC, jdamerow commented
Make it so, Jenkins.

2022-09-06 15:47 UTC, jdamerow commented
Make it so, Jenkins.

2022-09-06 15:51 UTC, jdamerow commented
There is a weird bug on the public site. I think the text in the textbox is also printed behind the box and doesn't scroll there.
![image](https://user-images.githubusercontent.com/8881141/188680309-a6d889e2-9570-4f64-937d-ac2f3f2b227f.png)

2022-09-16 19:17 UTC, tusanand commented
Fixed the bug where the text blocks were loading twice on exhinition page.
Fixed all indentation and Unit test case issues

2022-09-20 14:59 UTC, jdamerow commented
Make it so, Jenkins.

2022-09-20 15:02 UTC, merged