Story/vspc 149
diging/virtual-spaces-2.0 pull request #211
Opened 2021-05-06 22:36 UTC by AvirupBiswas

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 
Just to check whether the code is flowing in this branch from local
...Put description here...
  
## Anything else the reviewer needs to know?

... describe here ...

2021-05-06 22:37 UTC, jdamerow commented
Resolve conflicts please

2021-05-11 16:57 UTC, jdamerow requested changes

2021-05-11 16:57 UTC, jdamerow commented on vspace/src/main/webapp/resources/extra/Module_1.css
> +>>>>>>> develop
?

2021-05-12 15:23 UTC, jdamerow requested changes

2021-05-12 15:23 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/DashboardController.java
> +}
?

2021-05-13 16:45 UTC, jdamerow commented
Make it so, Jenkins.

2021-05-13 16:54 UTC, jdamerow commented
- navigation items in left navbar need to be centered
- logout icon still has a grey background
- link that has hover title "Exhibition Space" should say "Go to exhibition"
- contents of pages doesn't seem to be centered (there is more space on the left from navbar to content than on the right)
- bottom of side navbar, where it says "Virtual Spaces 2.0  DigInG 2020" is breaking after the first 20:
```
Virtual Spaces 2.0  DigInG 20
20
```

2021-05-19 16:48 UTC, jdamerow commented
This ticket is just for the layout tweaks, right? It shouldn't have any text block files.

2021-05-19 16:48 UTC, closed without merging

2021-05-19 20:04 UTC, AvirupBiswas commented
> This ticket is just for the layout tweaks, right? It shouldn't have any text block files.

Yes the ticket was just for layout tweaks but after resolving the merge conflict I got these changes.