Story/vspc 196
diging/virtual-spaces-2.0 pull request #270
Opened 2021-12-17 18:39 UTC by pradeep-017

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

Using existing images for space links, module links and external links
  
## Anything else the reviewer needs to know?

... describe here ...

2022-01-13 15:24 UTC, jdamerow requested changes
This also applies to javascript:
"I do not have any sysout statements in my code or commented out code that isn’t needed anymore"

2022-01-13 15:24 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/LinkManager.java
> +    protected void setDisplayProperties(ILinkDisplay linkDisplay,String id, float positionX,float positionY,int rotation, DisplayType displayType, byte[] linkImage, String imageFilename, String exist
this method should be overloaded (one method takes an image and one takes an image id).

2022-01-13 15:24 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/slides/slide.html
> +            	debugger;
?

2022-02-04 16:37 UTC, jdamerow requested changes

2022-02-04 16:37 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/LinkManager.java
> +    protected void setDisplayProperties(ILinkDisplay linkDisplay,String id, float positionX,float positionY,int rotation, DisplayType displayType, byte[] linkImage, String imageFilename, String exist
there are a bunch of parameters here that don't seem to be used in this method.

2022-02-04 16:37 UTC, jdamerow commented on vspace/src/test/java/edu/asu/diging/vspace/core/services/impl/SpaceLinkManagerTest.java
> +        //For spaceLink updating with existing Image
that should be its own test

2022-02-04 16:37 UTC, closed without merging

2022-02-28 18:41 UTC, pradeep-017 commented
Closing this. Will be tracked in https://github.com/diging/virtual-spaces-2.0/pull/247