Bug/vspc 207
diging/virtual-spaces-2.0 pull request #286
Opened 2022-04-04 23:11 UTC by swetalina-prusty25

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

2022-04-04 23:22 UTC, swetalina-prusty25 commented
finished the development of an image search field that allows users to search for images by name, file name, and description. It will filter the images.

2022-04-05 15:20 UTC, jdamerow requested changes

2022-04-05 15:20 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/data/ImageRepository.java
> +    List<VSImage> findByFilenameLikeOrNameLikeOrDescriptionLike(String filename, String name ,String Description);
variables/parameter names are lowercased

2022-04-05 15:20 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/data/ImageRepository.java
> +    List<VSImage> findByFilenameLikeOrNameLikeOrDescriptionLike(String filename, String name ,String Description);
also, blank goes after not before the comma

2022-04-05 15:20 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ImageService.java
> +    public List<IVSImage> findByFilenameOrNameContainsOrDescription(String searchTerm) {
just call this method `search`

2022-04-05 15:20 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ImageService.java
> +    public List<IVSImage> findByFilenameOrNameContainsOrDescription(String searchTerm) {
also javadoc is missing

2022-04-05 15:20 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/api/ImageSearchApiController.java
> +    @RequestMapping("/staff/images/searchImagesncd")
let's make this `/staff/images/search/full`

2022-04-05 15:20 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/api/ImageSearchApiController.java
> +    public String searchImageDescription(@RequestParam(value = "searchText", required = false) String searchTerm , Model model, RedirectAttributes attributes) {
this method should be in its own controller

2022-04-05 15:20 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/images/imagelist.html
> +                			$("#searchImageLink").attr('href','[[@{/staff/images/searchImagesncd?searchText=}]]'+$("#searchImageField").val());
indentation

2022-04-05 15:20 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/sequences/sequence.html
> -<html layout:decorate="~{layouts/main_staff}">
why is this file being deleted?

2022-04-05 15:21 UTC, jdamerow commented
The ticket description is not from the right ticket?

2022-04-05 15:21 UTC, closed without merging