Bug/vspc 210
diging/virtual-spaces-2.0 pull request #291
Opened 2022-04-18 21:52 UTC by swetalina-prusty25

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

2022-04-18 21:55 UTC, swetalina-prusty25 commented
Implemented the direct link to a space on the staff side to public side space.

2022-05-05 19:57 UTC, jdamerow requested changes

2022-05-05 19:57 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +            <a th:href="@{'/exhibit/space/'+${space?.id}}" class="btn primary-btn" style="float: right; margin-right: 39rem">Public Space</a>
this doesn't look like it belongs into this ticket.

2022-05-05 19:57 UTC, jdamerow commented
Wait, what is this PR about. You commented 
> On staff side: when clicking the drop down menu for a sequence (to edit title or description), the drop down menu says "edit Slide title" and "slide description" instead of sequence title, etc.
so changed the values to "edit sequence title" ,etc.
But that's not right, is it?

2022-05-05 19:58 UTC, jdamerow commented
Please figure out what actually belongs into this pr and fix ticket description.

2022-09-02 18:24 UTC, swetalina-prusty25 commented
Fixed ticket description which is Staff side space: there should be a link to the public side of a space.
code changes are in spcae.html fils

2022-09-06 19:01 UTC, swetalina-prusty25 commented on vspace/src/main/webapp/WEB-INF/views/staff/modules/sequences/sequence.html
>  				Created on <span class="date">[[${sequence.creationDate}]]</span> by
sequence.html file doesn't belongs to this ticket, so removed it.
only space.html file has the required changes for this ticket.

2022-09-06 22:13 UTC, swetalina-prusty25 commented
Copied the exact version for sequence.html from develop

2022-09-09 14:55 UTC, jdamerow commented
Make it so, Jenkins.

2022-09-09 15:02 UTC, jdamerow commented
That should not be a button but an icon. And since it doesn't have anything to do with creating link or editing the space in any way, it should also not be with the buttons to create links.
![image](https://user-images.githubusercontent.com/8881141/189380959-7839487a-2a4d-4fa6-b0c3-f28ec708be8b.png)
Please read https://diging.atlassian.net/wiki/spaces/DIGING/pages/3056304129/Basic+Webpage+Design+Guidelines and let me know if there are other information that would help you with webpage layout/design.

2022-09-09 15:02 UTC, closed without merging