Story/vspc 172
diging/virtual-spaces-2.0 pull request #294
Opened 2022-05-06 04:43 UTC by bnayak4

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

...Put description here...
  
## Anything else the reviewer needs to know?

... describe here ...

2022-05-25 20:19 UTC, jdamerow commented
Codefactor failed.

2023-11-21 20:56 UTC, jdamerow requested changes
there are a bunch of wrong indented lines introduced here, please fix

2023-11-21 20:56 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/LinkManager.java
> +        else {
please follow our style guide

2023-11-21 20:56 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/LinkManager.java
> +        else {
same here, code style

2023-11-21 20:56 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/LinkManager.java
> +
too many empty lines

2023-11-21 20:56 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/LinkManager.java
> +            String linkLabel, String linkDesc,String linkId,  String linkDisplayId, DisplayType displayType, byte[] linkImage,
there should be one space between `,String` and only one space after the comma (`,  String`)

2023-11-21 20:56 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddExternalLinkController.java
> +                externalLink, title,desc, type, linkImage, filename, externalLinkOpenMode, imageId);
blank missing: `title,desc`

2023-11-21 20:56 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddModuleLinkController.java
> +			throws NumberFormatException, SpaceDoesNotExistException, IOException, ImageCouldNotBeStoredException, ImageDoesNotExistException {
Indentation

2023-11-21 20:56 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddModuleLinkController.java
> +					linkedModuleId, moduleLinkLabel, moduleLinkDesc, type, linkImage, filename, imageId);
why is the indentation changed here?

2023-11-21 20:57 UTC, jdamerow commented
Make it so, Jenkins.

2023-11-21 20:59 UTC, jdamerow commented
Tests failed:
```
test_updateLink_success(edu.asu.diging.vspace.core.services.impl.ExternalLinkManagerTest)  Time elapsed: 0.038 sec  <<< ERROR!
java.lang.StackOverflowError
	at edu.asu.diging.vspace.core.services.impl.ExternalLinkManager.updateLink(ExternalLinkManager.java:156)
```

2023-12-01 14:19 UTC, jdamerow requested changes

2023-12-01 14:19 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +                                <option th:value="ARROW">Link</option>
why is this here twice?

2023-12-01 14:19 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +                    <input type="hidden" name="moduleLinkImageIdEdit" id="moduleLinkImageIdEdit" />
what is this for?

2023-12-01 14:19 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/EditModuleLinkController.java
> +            String[] token = moduleLinkImageIdEdit.split("/");
what is `moduleLinkImageIdEdit` and why does it need to be split?

2023-12-01 14:19 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/EditSpaceLinkController.java
> +			SpaceDoesNotExistException, LinkDoesNotExistsException, IOException, ImageCouldNotBeStoredException, ImageDoesNotExistException {
indentation of this whole block is too much

2023-12-01 14:19 UTC, jdamerow commented on vspace/src/main/webapp/WEB-INF/views/staff/spaces/space.html
> +            			'<span><img src="' + tbaseUrl + image.id + '" class="img-thumbnail" /> ' + image.text + '</span>'
indentation

2023-12-01 14:19 UTC, closed without merging

2025-10-15 17:17 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/core/services/impl/ContentBlockManager.java
> +    }
why is this method needed? why not just modifying the existing one? It's only called once, right?

2025-10-15 17:21 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/AddExternalLinkController.java
> +        if (file == null && imageId == null) {
not every link needs to have an image, e.g. if they use the default icon. Won't this break any other case?

2025-10-15 17:22 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/StaffSearchSpaceController.java
> +    private ISpaceManager spaceManager;
is this used anywhere? are any of the changes in this file needed?

2025-10-15 17:22 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/UpdateContentOrderController.java
> +            System.out.println(contentBlockString);
remove

2025-10-15 17:23 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/UpdateContentOrderController.java
> +        } catch (Exception e) {
exceptions should be specific or is `Exception` really thrown here (in this case, there should be a comment here).

2025-10-15 17:23 UTC, jdamerow commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/UpdateContentOrderController.java
> +            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
when is this thrown? does it always indicate a bad request?

2025-10-17 22:51 UTC, Girik1105 commented on vspace/src/main/java/edu/asu/diging/vspace/web/staff/StaffSearchSpaceController.java
> +    private ISpaceManager spaceManager;
Removed the unused ISpaceManager dependency and unused imports.